### PR TITLE
Feature/78 correct building address

### LINKED ISSUE #78: Correct building address in selected year
Currently we are showing the first address from the array of addresses.
The building address should be selected based on the selected year.

### PR DESCRIPTION
**Pull request by lraivio**
Closes #78.

### CODE REVIEW

**Comment by YoYuUm** [comment]
Probably the street years should fit the years of the school being in that building:

screen shot 2015-06-04 at 11 55 11

**Comment by lraivio** [comment]
Yeah these kind of situations are tricky. Optimally the data we get from the API would already be in sync and there would be no need for us to change it. In this case we could limit the upper and lower years of the addresses based on the building years. But the other building in this school (years 1906 - 1912) also has the Karviaistie 3 (1946 -> ) as an address. What would we show then when the address years are completely outside the building years.

**Comment by YoYuUm** [comment]
The address years are related with the building. So it depends on what we want to show in this field. 
Currently the first row is showing the building information and the box have the school-building years.
The addresses are showing the information related with the building but not the school.

If everything would be related with the school-building, the first line should filter out the names of the building streets which are out from the school-building period. And the list of addresses should include only those addresses, limiting the years to the years of school-building as well.

If an address is repeated but in different buildings we could show them in each building within the year limits of that school-building.

I don't know if I made any sense, if something was confusing please ask! :D

**Comment by lraivio** [comment]
Actually that makes a lot of sense :)

**Pull request merged**
