### PR TITLE
Add chrome to Travis test environment

### LINKED ISSUE #178: Add Chrome to test setup

### PR DESCRIPTION
**Pull request by vikoivun**
Use Chromeheadless to run tests, this makes them work within Travis.

### CODE REVIEW

**Comment by hukka** [comment]
Travis does not pass. Is that... expected?

**Comment by jussiarpalahti** [comment]
I just note that it's interesting that Node LTS works, yet "latest" Node doesn't.

Also that using headless Chrome in Travis has become so easy.

**Comment by vikoivun** [comment]
Yes indeed, this does not work with latest node yet, only with LTS. The idea at this point is to have some automatic build working. Next step is to start upgrading dependencies.

**Comment by jussiarpalahti** [comment]
Well, this seems to be what fails. On LTS:
`DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead`

and subsequently on latest Node:

`
  /home/travis/build/City-of-Helsinki/kore-ui/node_modules/socket.io/lib/store.js:35  
  Store.prototype.__proto__ = EventEmitter.prototype;
  TypeError: Cannot read property 'prototype' of undefined
`

**Comment by hukka** [comment]
Ah, yes. It didn't build at all before. Sure, LTS is better than nothing... Also nice that headless Chrome works like that now. We should update other repos too!

**Pull request merged**
