### PR TITLE
Feature/9 school filters

### LINKED ISSUE #9: Search page - filters
Ask guys from the archive for list of the most important filters.

### PR DESCRIPTION
**Pull request by YoYuUm**
closes #9

### CODE REVIEW

**Comment by lraivio** [comment]
Rebase would be in order.

**Comment by YoYuUm** [comment]
Wops...

**Comment by lraivio** [comment]
There is now an additional loader icon visible in the "Näytä lisää kouluja" -button.

**Comment by lraivio** [comment]
When coming back to search page from a school page, the filter values are in numbers. For example if I search with the language filter set to "ruotsi", select one of the schools and then come back to search page, the language filter shows "2".

**Comment by lraivio** [comment]
The schoolField filter is only showing the loading spinner. Was the API endpoint for requesting the options still not implemented?

**Comment by YoYuUm** [comment]
The API is still returning the options with the name in the description field :(

**Comment by YoYuUm** [comment]
I have changed the id field to a string in the SearchFilterControl select. That fixes up the bug with the numbers. Good catch.

**Comment by lraivio** [comment]
Looks good! :+1:

**Pull request merged**
